# fly.toml app configuration file generated for remplasveltenew on 2023-11-28T21:02:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "remplasveltenew"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
